# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "Modelo de Clasificación Binaria para la Predicción de Abandono de Clientes a partir de Datos de Suscripción: Dataset Telco Customer Churn"
author: Laura S. Rivera Figueredo y Natalý A. Cárdenas Izaquita
logo: Imagenes/logo.png

execute:
  execute_notebooks: "off"

html:
  extra_css:
    - style/custom.css
  use_issues_button: true
  use_repository_button: true
  use_download_button: true
  use_edit_page_button: true

sphinx:
  config:
    html_theme_options:
      default_mode: "dark"
  extra_extensions:
    - sphinx_design

favicon: Imagenes/favicon.ico

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/Nataly-Cardenas/Telco_Churn_Entregable
  branch: main